### ISSUE TITLE
Doesn't work on understrap theme

### ISSUE THREAD

**Issue by mbtocalli** [seb86/alnp-code-snippet-library#1]
I can't make it work using understrap theme
I enqueue the script using the following code in my functions.php:
`wp_enqueue_script( 'alnp-post-limit', get_stylesheet_directory_uri() . '/js/alnp-post-limit.js', true );`
and I put the snippet code in my 'js' folder

**Comment by seb86** [comment]
I would check your [parameters](https://developer.wordpress.org/reference/functions/wp_enqueue_script/#parameters). It looks like you skipped two of them.

**Comment by mbtocalli** [comment]
I'm using all parameters now and it still doesn't work
`wp_enqueue_script( 'alnp-post-limit', get_stylesheet_directory_uri() . '/js/alnp-post-limit.js', array(), false, true );`

**Comment by seb86** [comment]
@mbtocalli Are you placing it in your `functions.php` file as is or are you actually hooking it in?

**Comment by mbtocalli** [comment]
in my functions.php, along with my other required scripts

**Comment by seb86** [comment]
I don't know what else to suggest @mbtocalli

**Comment by mbtocalli** [comment]
thanks anyway. I will try updating the theme and I will let you know
